### ISSUE TITLE
How to use as CLI?

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [jvanbruegge/commithelper#1]
Hi Jan Van,
I liked your project and am using it to create standardized rules for the company I work for. Being able to use the same rules on the 'prepare-commit-msg' and 'commit-msg' hooks is very good.
One question I have is:
Is it possible to use the 'prompt' part via CLI, the same as when running 'npx git-cz'?
I'm trying to use via CLI and just display the message in the terminal, I tried setting '--file' to .'git/COMMIT_EDITMSG' without success.
I would like to be able to run via CLI and continue using also on the 2 hooks I mentioned.
If you have any north I can help you in PR.

**Comment by jvanbruegge** [comment]
Can you tell me what is not working exactly? Because `npx commithelper prompt` should work as expected
